version: '2'
services:
  spark-master:
    image: houshuai0816/spark-master:2.3.0-hadoop2.7
    container_name: spark-master
    restart: always
    networks:
      - front-tier
      - back-tier
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
  spark-worker-1:
    image: houshuai0816/spark-worker:2.3.0-hadoop2.7
    container_name: spark-worker-1
    restart: always
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    networks:
      - front-tier
      - back-tier
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
networks: 
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge