version: '2'
services:
  hadoop-master:
    image: houshuai0816/hadoop-master:3.1.0
    container_name: hadoop-master
    restart: always
    networks:
      - front-tier
      - back-tier
    ports:
      - "8088:8088"
      # - "7077:7077"
    # environment:
    #   - INIT_DAEMON_STEP=setup_spark
  hadoop-worker-1:
    image: houshuai0816/hadoop-worker:3.1.0
    container_name: hadoop-worker-1
    restart: always
    depends_on:
      - hadoop-master
    # ports:
    #   - "8081:8081"
    networks:
      - front-tier
      - back-tier
    # environment:
    #   - "SPARK_MASTER=spark://spark-master:7077"
  hadoop-worker-2:
    image: houshuai0816/hadoop-worker:3.1.0
    container_name: hadoop-worker-2
    restart: always
    depends_on:
      - hadoop-master
    # ports:
    #   - "8081:8081"
    networks:
      - front-tier
      - back-tier
    # environment:
    #   - "SPARK_MASTER=spark://spark-master:7077"
networks: 
  front-tier:
    driver: master
  back-tier:
    driver: serverb