version: '2'
services:
  hadoop-master:
    # image: houshuai0816/hadoop-master:3.1.0
    build: ./master/
    container_name: hadoop-master
    restart: always
    networks:
      app_net:
        ipv4_address: 10.10.1.30
    ports:
      - "8088:8088"
      - "9000:9000"
      - "50070:50070"
      - "32770:22"
    # links:
    #   - hadoop-slave1
    #   - hadoop-slave2
    extra_hosts:
      - "hadoop-master:10.10.1.30"
      - "hadoop-slave1:10.10.1.31"
      - "hadoop-slave2:10.10.1.32"
  hadoop-slave1:
    build: ./worker/
    container_name: hadoop-slave1
    restart: always
    networks:
      app_net:
        ipv4_address: 10.10.1.31
    # links:
    #   - hadoop-master
    #   - hadoop-slave2
    extra_hosts:
      - "hadoop-master:10.10.1.30"
      - "hadoop-slave1:10.10.1.31"
      - "hadoop-slave2:10.10.1.32"
  hadoop-slave2:
    build: ./worker/
    container_name: hadoop-slave2
    restart: always
    networks:
      app_net:
        ipv4_address: 10.10.1.32
    # links:
    #   - hadoop-slave1
    #   - hadoop-slave2
    extra_hosts:
      - "hadoop-master:10.10.1.30"
      - "hadoop-slave1:10.10.1.31"
      - "hadoop-slave2:10.10.1.32"
networks:
 app_net:
  driver: macvlan
  driver_opts:
    parent: eth0.10
  ipam:
    config:
      - subnet: 10.10.1.0/24
      - gateway: 10.10.1.2