version: '2'
services:
  hadoop-master:
    # image: houshuai0816/hadoop-master:3.1.0
    build: ./master/
    container_name: hadoop-master
    restart: always
    networks:
      - master
      - slave1
      - slave2
    depends_on:
      - hadoop-slave1
      - hadoop-slave2
    ports:
      - "8088:8088"
      - "9000:9000"
      - "50070:50070"
      - "32770:22"
    # extra_hosts:
    #   - "hadoop-master:192.168.2.10"
    #   - "hadoop-slave1:192.168.2.11"
    #   - "hadoop-slave2:192.168.2.12"
    #   - "hadoop-slave3:192.168.2.13"
  hadoop-slave1:
    build: ./worker/
    container_name: hadoop-slave1
    restart: always
    networks:
      - master
      - slave1
      - slave2
    # extra_hosts:
    #   - "hadoop-master:192.168.2.10"
    #   - "hadoop-slave1:192.168.2.11"
    #   - "hadoop-slave2:192.168.2.12"
    #   - "hadoop-slave3:192.168.2.13"
  hadoop-slave2:
    build: ./worker/
    container_name: hadoop-slave2
    restart: always
    networks:
      - master
      - slave1
      - slave2
    # extra_hosts:
    #   - "hadoop-master:192.168.2.10"
    #   - "hadoop-slave1:192.168.2.11"
    #   - "hadoop-slave2:192.168.2.12"
    #   - "hadoop-slave3:192.168.2.13"
networks: 
  master:
    driver: bridge
  slave1:
    driver: bridge
  slave2:
    driver: bridge