version: '2'
services:
  hadoop-master:
    image: houshuai0816/hadoop-master:3.1.0
    container_name: hadoop-master
    restart: always
    networks:
      - front-tier
      - back-tier
    depends_on:
      - hadoop-worker-1
      - hadoop-worker-2
    ports:
      - "8088:8088"
      - "9000:9000"
      - "50070:50070"
      - "32770:22"
    extra_hosts:
      - "hadoop-master:192.168.2.10"
      - "hadoop-slave1:192.168.2.11"
      - "hadoop-slave2:192.168.2.12"
      - "hadoop-slave3:192.168.2.13"
  hadoop-worker-1:
    image: houshuai0816/hadoop-worker:3.1.0
    container_name: hadoop-worker-1
    restart: always
    networks:
      - front-tier
      - back-tier
    extra_hosts:
      - "hadoop-master:192.168.2.10"
      - "hadoop-slave1:192.168.2.11"
      - "hadoop-slave2:192.168.2.12"
      - "hadoop-slave3:192.168.2.13"
  hadoop-worker-2:
    image: houshuai0816/hadoop-worker:3.1.0
    container_name: hadoop-worker-2
    restart: always
    networks:
      - front-tier
      - back-tier
    extra_hosts:
      - "hadoop-master:192.168.2.10"
      - "hadoop-slave1:192.168.2.11"
      - "hadoop-slave2:192.168.2.12"
      - "hadoop-slave3:192.168.2.13"
networks: 
  front-tier:
    driver: master
  back-tier:
    driver: serverb